version: '3.8'

services:
  backend:
    image: lcdamy/umurava-challenge-1-api:1.3
    platform: linux/x86_64
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/umurava-challenge-db
      - TOKEN_SECRET=HFKJDSHFKJHSJKD5654FDSJBFHDSHFSDFSD45646FSDBFHDSBFHDSF
      - COMMUNITY_INVITE_LINK=https://chat.whatsapp.com/GihQ5kUcxL0KcwEjz9rTJf

  mongo:
    image: mongo
    platform: linux/x86_64
    ports:
      - "27017:27017"
    
  
  frontend:
    image: lcdamy/umurava-challenge-1-frontend:1.3
    platform: linux/x86_64
    ports:
     - "3000:3000"
