import mongoose from 'mongoose';
import Skill from '../models/skillsModel'; // Adjust the path if necessary ../models/Skill
import dotenv from 'dotenv';
dotenv.config();

const seedSkills = async () => {
    try {
        // Connect to your MongoDB database
          await mongoose.connect(process.env.MONGO_URI || 'mongodb+srv://zudanga:a15LoLgUAHKn9Tfv@cluster0.djtfu.mongodb.net/umurava-challenge-db-api?retryWrites=true&w=majority&appName=Cluster0');

        console.log('Connected to the database.');

        // Define the skills to seed
        const skills = [
            { skillName: 'Python', status: 'active' },
            { skillName: 'Java', status: 'active' },
            { skillName: 'C#', status: 'active' },
            { skillName: 'PHP', status: 'active' },
            { skillName: 'C', status: 'active' },
            { skillName: 'Rust', status: 'active' },
            { skillName: 'Vue.js', status: 'active' },
            { skillName: 'Ruby on Rails', status: 'active' },
            { skillName: 'Django', status: 'active' },
            { skillName: 'Spring', status: 'active' },
            { skillName: 'Express.js', status: 'active' },
            { skillName: 'Flutter', status: 'active' },
            { skillName: 'React Native', status: 'active' },
            { skillName: 'Xamarin', status: 'active' },
            { skillName: 'TensorFlow', status: 'active' },
            { skillName: 'PyTorch', status: 'active' },
            { skillName: 'Scikit-learn', status: 'active' },
            { skillName: 'C++', status: 'active' },
            { skillName: 'HTML', status: 'active' },
            { skillName: 'CSS', status: 'active' },
            { skillName: 'JavaScript', status: 'active' },
            { skillName: 'Swift', status: 'active' },
            { skillName: 'Kotlin', status: 'active' },
            { skillName: 'UI/UX Design', status: 'active' },
            { skillName: 'UX Research', status: 'active' },
            { skillName: 'SQL', status: 'active' },
            { skillName: 'Golang', status: 'active' },
            { skillName: 'Angular', status: 'active' },
            { skillName: 'Oracle', status: 'active' },
            { skillName: 'Data Modeling', status: 'active' },
            { skillName: 'Performance Tuning', status: 'active' },
            { skillName: 'Backup', status: 'active' },
            { skillName: 'Recovery', status: 'active' },
            { skillName: 'Configuration', status: 'active' },
            { skillName: 'Troubleshooting', status: 'active' },
            { skillName: 'Network Security', status: 'active' },
            { skillName: 'CI/CD Pipelines', status: 'active' },
            { skillName: 'Automation Tools', status: 'active' },
            { skillName: 'Cloud Services', status: 'active' },
            { skillName: 'Scripting Languages', status: 'active' },
            { skillName: 'React', status: 'active' },
            { skillName: 'Responsive Design', status: 'active' },
            { skillName: 'Node.js', status: 'active' },
            { skillName: 'Database Management', status: 'active' },
            { skillName: 'API Development', status: 'active' },
            { skillName: 'AWS', status: 'active' },
            { skillName: 'Azure', status: 'active' },
            { skillName: 'Google Cloud', status: 'active' },
            { skillName: 'Digital Ocean', status: 'active' },
            { skillName: 'Architecture Design', status: 'active' },
            { skillName: 'Cost Management', status: 'active' },
            { skillName: 'Linear Algebra', status: 'active' },
            { skillName: 'Calculus', status: 'active' },
            { skillName: 'Probability', status: 'active' },
            { skillName: 'Statistics', status: 'active' },
            { skillName: 'Keras', status: 'active' },
            { skillName: 'SageMaker', status: 'active' },
            { skillName: 'Apache Airflow', status: 'active' },
            { skillName: 'Apache Kafka', status: 'active' },
            { skillName: 'Snowflake', status: 'active' },
            { skillName: 'Dbt', status: 'active' },
            { skillName: 'Microsoft Azure', status: 'active' },
            { skillName: 'User Research', status: 'active' },
            { skillName: 'Wireframing', status: 'active' },
            { skillName: 'Prototyping', status: 'active' },
            { skillName: 'Visual Design', status: 'active' },
            { skillName: 'Usability Testing', status: 'active' },
            { skillName: 'Figma', status: 'active' },
            { skillName: 'Marketo', status: 'active' },
            { skillName: 'Active Campaign', status: 'active' },
            { skillName: 'Adobe Photoshop', status: 'active' },
            { skillName: 'Adobe Illustrator', status: 'active' },
            { skillName: 'Adobe Premiere Pro', status: 'active' },
            { skillName: 'Final Cut Pro', status: 'active' },
            { skillName: 'DaVinci Resolve', status: 'active' },
            { skillName: 'Adobe Audition', status: 'active' },
            { skillName: 'Audacity', status: 'active' },
            { skillName: 'GarageBand', status: 'active' },
            { skillName: 'Trello', status: 'active' },
            { skillName: 'Asana', status: 'active' },
            { skillName: 'Notion', status: 'active' },
            { skillName: 'ClickUp', status: 'active' },
            { skillName: 'MondayCom', status: 'active' },
            { skillName: 'Jasper', status: 'active' },
            { skillName: 'Adobe Firefly', status: 'active' },
            { skillName: 'Adobe Dreamweaver', status: 'active' },
            { skillName: 'Sketch', status: 'active' },
            { skillName: 'Adobe After Effects', status: 'active' },
            { skillName: 'Blender', status: 'active' },
            { skillName: 'Toon Boom Harmony', status: 'active' },
            { skillName: 'SPSS', status: 'active' },
            { skillName: 'MySQL', status: 'active' },
            { skillName: 'PostgreSQL', status: 'active' },
            { skillName: 'MongoDB', status: 'active' },
            { skillName: 'Jotform', status: 'active' },
            { skillName: 'SurveySparrow', status: 'active' },
            { skillName: 'Kobo Toolbox', status: 'active' },
            { skillName: 'FastField', status: 'active' },
            { skillName: 'Tableau', status: 'active' },
            { skillName: 'Case Studies', status: 'active' },
            { skillName: 'Web Analytics', status: 'active' },
            { skillName: 'Customer Segmentation', status: 'active' },
            { skillName: 'SEO', status: 'active' },
            { skillName: 'SEM', status: 'active' },
            { skillName: 'Social Media Management', status: 'active' },
            { skillName: 'WordPress', status: 'active' },
            { skillName: 'Shopify', status: 'active' },
            { skillName: 'WooCommerce', status: 'active' },
            { skillName: 'Leadership', status: 'active' },
            { skillName: 'Strategic Planning', status: 'active' },
            { skillName: 'Financial Forecasting', status: 'active' },
            { skillName: 'Project Management', status: 'active' },
            { skillName: 'Decision Making', status: 'active' },
            { skillName: 'Process Optimization', status: 'active' },
            { skillName: 'Supply Chain Management', status: 'active' },
            { skillName: 'Quality Controls', status: 'active' },
            { skillName: 'Quality Assurance', status: 'active' },
            { skillName: 'Vendor Management', status: 'active' },
            { skillName: 'Technology Integration', status: 'active' },
            { skillName: 'Taxation', status: 'active' },
            { skillName: 'Financial Reporting', status: 'active' },
            { skillName: 'Investment Analysis', status: 'active' },
            { skillName: 'Quickbooks', status: 'active' },
            { skillName: 'SAP', status: 'active' },
            { skillName: 'Accounting Softwares', status: 'active' },
            { skillName: 'Workforce Planning', status: 'active' },
            { skillName: 'Training and Development', status: 'active' },
            { skillName: 'Succession Planning', status: 'active' },
            { skillName: 'Performance Management', status: 'active' },
            { skillName: 'Diversity and Inclusion', status: 'active' },
            { skillName: 'HR Softwares', status: 'active' },
            { skillName: 'Labor Laws', status: 'active' },
            { skillName: 'Business Acumen', status: 'active' },
            { skillName: 'Change Management', status: 'active' },
            { skillName: 'Conflict Resolution', status: 'active' },
            { skillName: 'Negotiation', status: 'active' },
            { skillName: 'Active Listening', status: 'active' },
            { skillName: 'Multitasking', status: 'active' },
            { skillName: 'Applicant Tracking Systems', status: 'active' },
            { skillName: 'Recruitment Softwares', status: 'active' },
            { skillName: 'Employer Branding', status: 'active' },
            { skillName: 'Job Advertising', status: 'active' },
            { skillName: 'Candidate Engagement', status: 'active' },
            { skillName: 'Empathy', status: 'active' },
            { skillName: 'Relationship Building', status: 'active' },
            { skillName: 'Time Management', status: 'active' },
            { skillName: 'Data Analysis', status: 'active' },
            { skillName: 'Cultural Competence', status: 'active' },
            { skillName: 'Psychology', status: 'active' },
            { skillName: 'Job Descriptions', status: 'active' },
            { skillName: 'Team Building', status: 'active' },
            { skillName: 'Payroll Management', status: 'active' },
            { skillName: 'Motivation', status: 'active' },
            { skillName: 'Agile', status: 'active' },
            { skillName: 'Signage Design', status: 'active' },
            { skillName: 'Social Media Marketing', status: 'active' },
            { skillName: 'Paid Social Media Design', status: 'active' },
            { skillName: 'Social Commerce', status: 'active' },
            { skillName: 'Influencer Marketing', status: 'active' },
            { skillName: 'Community Management', status: 'active' },
            { skillName: 'Video Marketing', status: 'active' },
            { skillName: 'E-Commerce Marketing', status: 'active' },
            { skillName: 'Email Marketing', status: 'active' },
            { skillName: 'Email Automation', status: 'active' },
            { skillName: 'Affiliate Marketing', status: 'active' },
            { skillName: 'Display Advertising', status: 'active' },
            { skillName: 'Public Relations', status: 'active' },
            { skillName: 'Text Message Marketing', status: 'active' },
            { skillName: 'Marketing Strategy', status: 'active' },
            { skillName: 'Brand Strategy', status: 'active' },
            { skillName: 'Digital Marketing Strategy', status: 'active' },
            { skillName: 'Marketing Concepts & Ideation', status: 'active' },
            { skillName: 'Conversion Rate Optimization', status: 'active' },
            { skillName: 'Content Writing', status: 'active' },
            { skillName: 'Articles & Blog Posts', status: 'active' },
            { skillName: 'Website Content', status: 'active' },
            { skillName: 'Scriptwriting', status: 'active' },
            { skillName: 'Creative Writing', status: 'active' },
            { skillName: 'Podcast Writing', status: 'active' },
            { skillName: 'Speechwriting', status: 'active' },
            { skillName: 'Proofreading & Editing', status: 'active' },
            { skillName: 'AI Content Editing', status: 'active' },
            { skillName: 'Localization', status: 'active' },
            { skillName: 'Resume Writing', status: 'active' },
            { skillName: 'Cover letters', status: 'active' },
            { skillName: 'LinkedIn Profiles', status: 'active' },
            { skillName: 'eLearning Content Development', status: 'active' },
            { skillName: 'Product Descriptions', status: 'active' },
            { skillName: 'Sales Copy', status: 'active' },
            { skillName: 'Email Copy', status: 'active' },
            { skillName: 'Ad Copy', status: 'active' },
            { skillName: 'Press Releases', status: 'active' },
            { skillName: 'UX Writing', status: 'active' },
            { skillName: 'Visual Effects', status: 'active' },
            { skillName: 'Video Editing', status: 'active' },
            { skillName: 'Intro & Outro Videos', status: 'active' },
            { skillName: 'Subtitles & Captions', status: 'active' },
            { skillName: 'Video Ads', status: 'active' },
            { skillName: 'Social Media Videos', status: 'active' },
            { skillName: 'Music Videos', status: 'active' },
            { skillName: 'Slideshow Videos', status: 'active' },
            { skillName: 'Animated Explainers', status: 'active' },
            { skillName: 'eLearning Video Production', status: 'active' },
            { skillName: 'Screencasting', status: 'active' },
            { skillName: 'Live Action Explainers', status: 'active' },
            { skillName: 'Logo Animation', status: 'active' },
            { skillName: 'Text Animation', status: 'active' },
            { skillName: '3D Product Animation', status: 'active' },
            { skillName: 'Data Analytics', status: 'active' },
            { skillName: 'Data Science', status: 'active' },
            { skillName: 'Machine Learning', status: 'active' },
            { skillName: 'Software Development', status: 'active' },
            { skillName: 'HR Consulting', status: 'active' },
            { skillName: 'Virtual Assistance', status: 'active' },
            { skillName: 'E-commerce Management', status: 'active' },
            { skillName: 'Event Management', status: 'active' },
            { skillName: 'Lead Generation', status: 'active' },
            { skillName: 'Call Center', status: 'active' },
            { skillName: 'Customer Care', status: 'active' },
            { skillName: 'Presentations', status: 'active' },
            { skillName: 'Career Counseling', status: 'active' },
            { skillName: 'Career Coaching', status: 'active' },
            { skillName: 'Training', status: 'active' },
            { skillName: 'SurveyCTO', status: 'active' }
        ];

        // Clear existing skills
        await Skill.deleteMany({});
        console.log('Existing skills cleared.');

        // Insert new skills
        await Skill.insertMany(skills);
        console.log('Skills seeded successfully.');

        // Close the database connection
        await mongoose.disconnect();
        console.log('Database connection closed.');
    } catch (error) {
        console.error('Error seeding skills:', error);
        process.exit(1);
    }
};

seedSkills();