name: run-api-ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install packages
        run: npm install

      - name: test
        run: npm test

      - name: build docker image
        run: docker build -t lcdamy/umurava-challenge-1-api:1.3 ./

      - name: log in to DockerHub
        run: echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: push docker image to dockerhub
        run: docker push lcdamy/umurava-challenge-1-api:1.3
